### ISSUE TITLE
cronjob failed adding: Failed to parse int from nil

### ISSUE THREAD

**Issue by patsevanton** [robertdebock/ansible-role-gitlab#2]
## Describe the bug
```
cronjob failed adding: Failed to parse int from nil: strconv.Atoi: parsing \"nil\": invalid syntax" command="/opt/gitlab/bin/gitlab-ctl renew-le-certs" spec="43 0 nil
```

## Inventory

```yaml
---
all:
  children:
    primarydomaincontroller:
      hosts:
        "dc2022":
          ansible_host: "51.250.37.195"
      vars:
        ansible_user: Administrator
        ansible_password: "xxxxxx"
        ansible_connection: winrm
        ansible_port: 5986
        ansible_winrm_transport: basic
        ansible_winrm_server_cert_validation: ignore
        pdc_administrator_password: "xxxxx"
        pdc_domain: "ad.domain.test"
        pdc_domain_path: "dc=ad,dc=domain,dc=test"
    gitlab:
      hosts:
        "gitlab":
          ansible_host: "51.250.39.199"
      vars:
        ansible_user:  ubuntu
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        gitlab_external_url: "https://gitlab.51.250.39.199.sslip.io"
        gitlab_letsencrypt: yes
        gitlab_letsencrypt_contact_emails:
          - you.email@gmail.com
        gitlab_letsencrypt_group: root
        gitlab_letsencrypt_key_size: 2048
        gitlab_letsencrypt_owner: root
        gitlab_letsencrypt_wwwroot: /var/opt/gitlab/nginx/www
        gitlab_letsencrypt_auto_renew: yes
        gitlab_letsencrypt_auto_renew_hour: 0
        gitlab_letsencrypt_auto_renew_minute: nil
        gitlab_letsencrypt_auto_renew_day_of_month: nil
        gitlab_letsencrypy_auto_renew_log_directory: /var/log/gitlab/lets-encrypt
```

## Playbook
```
- hosts: primarydomaincontroller
  roles:
    - role: justin_p.posh5
    - role: justin_p.wincom
    - role: justin_p.pdc

- hosts: gitlab
  become: yes
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
  roles:
    - role: robertdebock.gitlab
```

## Output

```
    [0m    Mixlib::ShellOut::ShellCommandFailed[0m
        ------------------------------------[0m
        Expected process to exit with [0], but received '1'
    [0m    ---- Begin output of /opt/gitlab/embedded/bin/sv restart /opt/gitlab/service/crond ----
    [0m    STDOUT: timeout: down: /opt/gitlab/service/crond: 0s, normally up, want up
    [0m    STDERR:
    [0m    ---- End output of /opt/gitlab/embedded/bin/sv restart /opt/gitlab/service/crond ----
    [0m    Ran /opt/gitlab/embedded/bin/sv restart /opt/gitlab/service/crond returned 1[0m

    [0m    Cookbook Trace:[0m
        ---------------[0m
        /opt/gitlab/embedded/cookbooks/cache/cookbooks/runit/libraries/helpers.rb:136:in `tap'
    [0m    /opt/gitlab/embedded/cookbooks/cache/cookbooks/runit/libraries/helpers.rb:136:in `safe_sv_shellout!'
    [0m    /opt/gitlab/embedded/cookbooks/cache/cookbooks/runit/libraries/helpers.rb:164:in `restart_service'
    [0m    /opt/gitlab/embedded/cookbooks/cache/cookbooks/runit/libraries/provider_runit_service.rb:357:in `block in <class:RunitService>'[0m

    [0m    Resource Declaration:[0m
        ---------------------[0m
        # In /opt/gitlab/embedded/cookbooks/cache/cookbooks/crond/recipes/enable.rb
    [0m
    [0m     15: runit_service "crond" do
    [0m     16:   owner "root"
    [0m     17:   group "root"
    [0m     18:   options({
    [0m     19:     cron_d: node['crond']['cron_d'],
    [0m     20:     log_directory: node['crond']['log_directory']
    [0m     21:   }.merge(params))
    [0m     22:   log_options log_options node['gitlab']['logging'].to_hash.merge(node["crond"].to_hash)
    [0m     23: end
    [0m
    [0m    Compiled Resource:[0m
        ------------------[0m
        # Declared in /opt/gitlab/embedded/cookbooks/cache/cookbooks/crond/recipes/enable.rb:15:in `from_file'
    [0m
    [0m    runit_service("crond") do
    [0m      action [:enable]
    [0m      updated true
    [0m      default_guard_interpreter :default
    [0m      declared_type :runit_service
    [0m      cookbook_name "crond"
    [0m      recipe_name "enable"
    [0m      service_name "crond"
    [0m      options {:env_dir=>"/opt/gitlab/sv/crond/env", :cron_d=>"/var/opt/gitlab/crond", :log_directory=>"/var/log/gitlab/crond"}
    [0m      log_options {"svlogd_size"=>209715200, "svlogd_num"=>30, "svlogd_timeout"=>86400, "svlogd_filter"=>"gzip", "svlogd_udp"=>nil, "svlogd_prefix"=>nil, "udp_log_shipping_host"nil, "udp_log_shipping_hostname"=>nil, "udp_log_shipping_port"=>514, "logrotate_frequency"=>"daily", "logrotate_maxsize"=>nil, "logrotate_size"=>nil, "logrotate_rotate"=>30, "logrotateompress"=>"compress", "logrotate_method"=>"copytruncate", "logrotate_postrotate"=>nil, "logrotate_dateformat"=>nil, "enable"=>true, "log_directory"=>"/var/log/gitlab/crond", "cron_d"=>var/opt/gitlab/crond"}
    [0m      owner "root"
    [0m      group "root"
    [0m      run_template_name "crond"
    [0m      log_template_name "crond"
    [0m      check_script_template_name "crond"
    [0m      finish_script_template_name "crond"
    [0m      control_template_names {}
    [0m    end
    [0m
    [0m    System Info:[0m
        ------------[0m
        chef_version=15.17.4
    [0m    platform=ubuntu
    [0m    platform_version=20.04
    [0m    ruby=ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-linux]
    [0m    program_name=/opt/gitlab/embedded/bin/chef-client
    [0m    executable=/opt/gitlab/embedded/bin/chef-client[0m

```

Log /var/log/gitlab/crond/current
```
2022-03-17_06:32:05.50206 time="2022-03-17T06:32:05Z" level=error msg="cronjob failed adding: Failed to parse int from nil: strconv.Atoi: parsing \"nil\": invalid syntax" command="/opt/gitlab/bin/gitlab-ctl renew-le-certs" spec="43 0 nil * *" user=root
2022-03-17_06:32:05.50207 time="2022-03-17T06:32:05Z" level=fatal msg="Failed to parse int from nil: strconv.Atoi: parsing \"nil\": invalid syntax"
2022-03-17_06:32:06.50758 time="2022-03-17T06:32:06Z" level=info msg="starting go-crond version 21.5.0 (d5c7f3b; go1.16.9) "
2022-03-17_06:32:06.50772 time="2022-03-17T06:32:06Z" level=info msg="{\"ShowVersion\":false,\"ShowOnlyVersion\":false,\"ShowHelp\":false,\"Cron\":{\"DefaultUser\":\"root\",\"IncludeCronD\":[\"/var/opt/gitlab/crond\"],\"Auto\":false,\"RunParts\":null,\"RunParts1m\":null,\"RunParts15m\":null,\"RunPartsHourly\":null,\"RunPartsDaily\":null,\"RunPartsWeekly\":null,\"RunPartsMonthly\":null,\"AllowUnprivileged\":false,\"WorkDir\":\"/\",\"EnableUserSwitching\":false},\"Log\":{\"Verbose\":false,\"Json\":false},\"Server\":{\"Bind\":\"\",\"Metrics\":false}}"
```

## Environment

- Control node OS: Ubuntu 20.04
- Control node Ansible version: core 2.12.2
- Managed node OS: Ubuntu 20.04

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).
