### ISSUE TITLE
When gitlab_distribution: community run test if enterprise item in gitlab_rails_ldap_servers is set correctly

### ISSUE THREAD

**Issue by patsevanton** [robertdebock/ansible-role-gitlab#4]
## Describe the bug

When gitlab_distribution: community run test if enterprise item in gitlab_rails_ldap_servers is set correctly

## Playbook

```yaml
---
- hosts: primarydomaincontroller
  roles:
    - role: justin_p.posh5
    - role: justin_p.wincom
    - role: justin_p.pdc
  post_tasks:
    - name: Ensure user gitlab_ldap_sync is present
      community.windows.win_domain_user:
        name: gitlab_ldap_sync
        password: "{{ pswd_gitlab_ldap_sync }}"
        state: present
        path: cn=Users,dc=ad,dc=domain,dc=test
    - name: Ensure OU Gitlab Users is present
      community.windows.win_domain_ou:
        name: GitlabUsers
        path: dc=ad,dc=domain,dc=test
        state: present
    - name: Ensure user test_user_in_pdc is present
      community.windows.win_domain_user:
        name: test_user_in_pdc
        password: "{{ pswd_test_user_in_pdc }}"
        state: present
        path: ou=GitlabUsers,dc=ad,dc=domain,dc=test

- hosts: gitlab
  become: yes
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
  roles:
    - role: robertdebock.gitlab
```

## Inventory
```
all:
  children:
    primarydomaincontroller:
      hosts:
        "dc2022":
          ansible_host: xxxxxxx
      vars:
        ansible_user: Administrator
        ansible_password: xxxxx
        ansible_connection: winrm
        ansible_port: 5986
        ansible_winrm_transport: basic
        ansible_winrm_server_cert_validation: ignore
        pdc_administrator_password: xxxxxx
        pdc_domain_safe_mode_password: xxxxx
        pdc_domain: "ad.domain.test"
        pdc_domain_path: "dc=ad,dc=domain,dc=test"
        pswd_gitlab_ldap_sync: xxxxxxx
        pswd_test_user_in_pdc: xxxxx
    gitlab:
      hosts:
        "gitlab":
          ansible_host: "51.250.35.153"
      vars:
        ansible_user:  ubuntu
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        gitlab_external_url: xxxxxx
        gitlab_letsencrypt: yes
        gitlab_letsencrypt_contact_emails:
          - you.email@gmail.com
        gitlab_letsencrypt_group: root
        gitlab_letsencrypt_key_size: 2048
        gitlab_letsencrypt_owner: root
        gitlab_letsencrypt_wwwroot: /var/opt/gitlab/nginx/www
        gitlab_letsencrypt_auto_renew: yes
        gitlab_letsencrypt_auto_renew_hour: 0
        gitlab_letsencrypt_auto_renew_minute: nil
        gitlab_letsencrypt_auto_renew_day_of_month: 7
        gitlab_letsencrypy_auto_renew_log_directory: /var/log/gitlab/lets-encrypt

        gitlab_rails_ldap_enabled: yes
        gitlab_rails_ldap_servers:
          - name: main
            label: LDAP
            host: xxxxxx
            port: 389
            uid: sAMAccountName
            bind_dn: CN=gitlab_ldap_sync,CN=Users,DC=ad,DC=domain,DC=test
            password: xxxxxxxx
            encryption: plain
            verify_certificates: no
            smartcard_auth: no
            active_directory: yes
            allow_username_or_email_login: no
            lowercase_usernames: no
            block_auto_created_users: no
            base: "DC=ad,DC=domain,DC=test"
            user_filter: "(memberof=OU=GitlabUsers,DC=ad,DC=domain,DC=test)"
```

## Output

```
TASK [robertdebock.gitlab : test if enterprise item in gitlab_rails_ldap_servers is set correctly] ***************************************************************************************
task path: /home/user/.ansible/roles/robertdebock.gitlab/tasks/assert.yml:160
failed: [gitlab -> localhost] (item=main) => changed=false
  ansible_loop_var: item
  assertion: item.group_base is defined
  evaluated_to: false
  item:
    active_directory: true
    allow_username_or_email_login: false
    base: DC=ad,DC=domain,DC=test
    bind_dn: CN=gitlab_ldap_sync,CN=Users,DC=ad,DC=domain,DC=test
    block_auto_created_users: false
    encryption: plain
    host: 51.250.43.175
    label: LDAP
    lowercase_usernames: false
    name: main
    password: atn7N7{Nud
    port: 389
    smartcard_auth: false
    uid: sAMAccountName
    user_filter: (memberof=OU=GitlabUsers,DC=ad,DC=domain,DC=test)
    verify_certificates: false
  msg: Assertion failed
```

## Environment

- Control node OS: Ubuntu 20.04
- Control node Ansible version: core 2.12.2
- Managed node OS: Ubuntu 20.04

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).
